let productos = [
  {
    id: 0,
    title: "Vue Js",
    price: 10,
    src: "../public/img/1.jpg",
    description: "Playera del Framework VueJs",
    stock: 10,
    category: "playeras",
  },
  {
    id: 1,
    title: "Angular Js",
    price: 20,
    src: "../public/img/2.jpg",
    description: "Playera del Framework Angular Js",
    stock: 10,
    category: "playeras",
  },
  {
    id: 2,
    title: "React Js",
    price: 20,
    src: "../public/img/3.jpg",
    description: "Playera de la librería React Js",
    stock: 10,
    category: "playeras",
  },
  {
    id: 3,
    title: "Redux Js",
    price: 20,
    src: "../public/img/4.jpg",
    description: "Playera de Redux Js",
    stock: 10,
    category: "playeras",
  },
  {
    id: 4,
    title: "Node Js",
    price: 20,
    src: "../public/img/5.jpg",
    description: "Playera de Node Js",
    stock: 10,
    category: "playeras",
  },
  {
    id: 5,
    title: "SASS",
    price: 20,
    src: "../public/img/6.jpg",
    description: "Playera de Sass",
    stock: 10,
    category: "playeras",
  },
  {
    id: 6,
    title: "HTML",
    price: 20,
    src: "../public/img/7.jpg",
    description: "Playera de HTML",
    stock: 10,
    category: "playeras",
  },
  {
    id: 7,
    title: "GitHub",
    price: 20,
    src: "../public/img/8.jpg",
    description: "Playera de GItHub",
    stock: 10,
    category: "playeras",
  },
  {
    id: 8,
    title: "BulmaCSS",
    price: 20,
    src: "../public/img/9.jpg",
    description: "Playera de Bulma CSS",
    stock: 10,
    category: "playeras",
  },
  {
    id: 9,
    title: "TypeScript",
    price: 20,
    src: "../public/img/10.jpg",
    description: "Playera de TypeScript",
    stock: 10,
    category: "playeras",
  },
  {
    id: 10,
    title: "Drupal",
    price: 20,
    src: "../public/img/11.jpg",
    description: "Playera de Drupal",
    stock: 10,
    category: "playeras",
  },
  {
    id: 11,
    title: "JavaScript",
    price: 20,
    src: "../public/img/12.jpg",
    description: "Playera de JavaScript",
    stock: 10,
    category: "playeras",
  },
  {
    id: 12,
    title: "GraphQL",
    price: 20,
    src: "../public/img/13.jpg",
    description: "Playera de Graph SQL",
    stock: 10,
    category: "playeras",
  },
  {
    id: 13,
    title: "WordPress",
    price: 20,
    src: "../public/img/14.jpg",
    description: "Playera de WordPress",
    stock: 10,
    category: "playeras",
  },

  /* gorras */
  {
    id: 14,
    title: "Gorra FrontEnd",
    price: 20,
    src: "../public/img/gorras/gorra1.jpg",
    description: "Gorra con HTML CSS y JS",
    stock: 10,
    category: "gorras",
  },

  {
    id: 16,
    title: "Gorra GitHub",
    price: 20,
    src: "../public/img/gorras/gorra3.webp",
    description: "Gorra con logo de GitHub",
    stock: 10,
    category: "gorras",
  },
  {
    id: 17,
    title: "Gorra .Net",
    price: 20,
    src: "../public/img/gorras/gorra4.jpg",
    description: "Gorra con .NET Core Color negro con morado",
    stock: 10,
    category: "gorras",
  },
  {
    id: 18,
    title: "Gorra Angular Js",
    price: 20,
    src: "../public/img/gorras/gorra5.webp",
    description: "Gorra con Angular en la parte de atrás",
    stock: 10,
    category: "gorras",
  },

  {
    id: 20,
    title: "Gorra Negra FrontEnd",
    price: 20,
    src: "../public/img/gorras/gorra7.jpg",
    description: "Gorra negra con texto de desarrollador FrontEnd",
    stock: 10,
    category: "gorras",
  },
  {
    id: 21,
    title: "Gorra Js",
    price: 20,
    src: "../public/img/gorras/gorra8.jpg",
    description: "Gorra con simbolo de JavaScript",
    stock: 10,
    category: "gorras",
  },
  {
    id: 22,
    title: "Gorra Python",
    price: 20,
    src: "../public/img/gorras/gorra9.jpg",
    description: "Gorra color blanco con símbolo de Python",
    stock: 10,
    category: "gorras",
  },

  /* sudaderas */

  {
    id: 24,
    title: "Sudadera Junior Dev",
    price: 20,
    src: "../public/img/sudaderas/sudadera2.jpg",
    description: "Sudadera color negro con cartel de Junior Developer",
    stock: 10,
    category: "sudaderas",
  },

  {
    id: 26,
    title: "Sudadera con código",
    price: 20,
    src: "../public/img/sudaderas/sudadera4.jpg",
    description: "Sudadera negra con fragmento de código impreso",
    stock: 10,
    category: "sudaderas",
  },
  {
    id: 27,
    title: "Sudadera IT software Dev",
    price: 20,
    src: "../public/img/sudaderas/sudadera5.jpg",
    description: "Sudadera negra con cartel de desarrollador de software",
    stock: 10,
    category: "sudaderas",
  },
  {
    id: 28,
    title: "Sudadera API",
    price: 20,
    src: "../public/img/sudaderas/sudadera6.jpg",
    description: "Sudadera gris con cartel de use my private API",
    stock: 10,
    category: "sudaderas",
  },
];

export let mockFetch = () => {
  return new Promise((resolve, reject) => {
    setTimeout(() => {
      resolve(productos);
    }, 3000);
  });
};
